apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-get-metrics
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-get-metrics
subjects:
  # prometheus is accessing kube-controller-manager and kube-scheduler /metrics
  # endpoint using apiserver proxy which in turn makes anonymous requests to
  # pods.
  - kind: User
    name: system:anonymous
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: prometheus-get-metrics
  apiGroup: rbac.authorization.k8s.io
