{{- if eq .Values.cni "cilium" }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "waitForCiliumCRDs.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-7"
    {{- include "waitForCiliumCRDs.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "waitForCiliumCRDs.name" . | quote }}
    {{- include "waitForCiliumCRDs.selectorLabels" . | nindent 4 }}
    role: {{ include "waitForCiliumCRDs.selector" . | quote }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: {{ include "waitForCiliumCRDs.name" . | quote }}
      {{- include "waitForCiliumCRDs.selectorLabels" . | nindent 6 }}
  # allow egress traffic to the Kubernetes API
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 6443
      protocol: TCP
    to:
    {{- range tuple "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
  # deny ingress traffic
  ingress: []
  policyTypes:
  - Egress
  - Ingress
{{- end }}
