{{- if eq .Values.cni "cilium" }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "waitForCiliumCRDs.name" . }}
  annotations:
    "helm.sh/hook-weight": "-6"
    {{- include "waitForCiliumCRDs.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "waitForCiliumCRDs.name" . | quote }}
    {{- include "waitForCiliumCRDs.selectorLabels" . | nindent 4 }}
    role: {{ include "waitForCiliumCRDs.selector" . | quote }}
spec:
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  hostPID: false
  hostIPC: false
  hostNetwork: false
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
{{- end }}
