{{- if eq .Values.cni "cilium" }}
{{- range $namespace := .Values.cilium.allowAllIngressFromHostIn }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-ingress-from-host
  namespace: {{ $namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}  
spec:
  endpointSelector: {}
  ingress:
  - fromEntities:
    - host
    - remote-node
{{- end }}
{{- end }}
