apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: etcd
spec:
  selector:
    matchLabels:
      component: etcd
  podMetricsEndpoints:
  - port: ""
    relabelings:
    - sourceLabels: [__address__]
      regex: ([^:]+)
      targetLabel: __address__
      replacement: ${1}:2381
      action: replace
